# questions.py

QUESTION_BANK = [
    # ==================== 高等数学 (60题) ====================
    {'id': 1, 'category': '高等数学', 'content': r"求极限 $\lim_{x \to 0} \frac{\sin x}{x}$。"},
    {'id': 2, 'category': '高等数学', 'content': r"计算极限 $\lim_{x \to \infty} (1 + \frac{1}{x})^x$。"},
    {'id': 3, 'category': '高等数学', 'content': r"求函数 $f(x) = x^3 - 3x + 1$ 的极大值点。"},
    {'id': 4, 'category': '高等数学', 'content': r"已知 $y = \ln(\tan x)$，求 $\frac{dy}{dx}$。"},
    {'id': 5, 'category': '高等数学', 'content': r"求函数 $y = e^{2x} \sin x$ 的导数。"},
    {'id': 6, 'category': '高等数学', 'content': r"计算不定积分 $\int x \cdot e^x dx$。"},
    {'id': 7, 'category': '高等数学', 'content': r"计算定积分 $\int_{0}^{\pi} \sin x dx$。"},
    {'id': 8, 'category': '高等数学', 'content': r"求曲线 $y = x^2$ 在 $x = 1$ 处的切线方程。"},
    {'id': 9, 'category': '高等数学', 'content': r"求函数 $f(x) = x \cdot |x|$ 的导函数 $f'(x)$。"},
    {'id': 10, 'category': '高等数学', 'content': r"利用洛必达法则计算 $\lim_{x \to \infty} \frac{\ln x}{x}$。"},
    {'id': 11, 'category': '高等数学', 'content': r"写出函数 $f(x) = e^x$ 的麦克劳林级数的前三项。"},
    {'id': 12, 'category': '高等数学', 'content': r"计算圆 $x^2 + y^2 = 4$ 围成的面积值。"},
    {'id': 13, 'category': '高等数学', 'content': r"计算曲线 $y=x^2$ 从 $x=0$ 到 $x=1$ 的弧长积分表达式。"},
    {'id': 14, 'category': '高等数学', 'content': r"求 $z = x^2 - y^2$ 在点 $(0,0)$ 处的黑塞矩阵。"},
    {'id': 15, 'category': '高等数学', 'content': r"计算向量场 $\mathbf{F} = (y, -x)$ 的散度。"},
    {'id': 16, 'category': '高等数学', 'content': r"计算向量场 $\mathbf{F} = (y, -x, 0)$ 的旋度。"},
    {'id': 17, 'category': '高等数学', 'content': r"求微分方程 $y' + y = 0$ 满足初值 $y(0)=1$ 的特解。"},
    {'id': 18, 'category': '高等数学', 'content': r"求微分方程 $y'' + y = 0$ 满足 $y(0)=0, y'(0)=1$ 的特解。"},
    {'id': 19, 'category': '高等数学', 'content': r"判断级数 $\sum_{n=1}^{\infty} \frac{1}{n}$ 的敛散性。"},
    {'id': 20, 'category': '高等数学', 'content': r"判断级数 $\sum_{n=1}^{\infty} \frac{1}{n^2}$ 的敛散性。"},
    {'id': 21, 'category': '高等数学', 'content': r"求函数 $f(x) = x^2$ 在区间 $[0, 2]$ 上满足拉格朗日中值定理的 $\xi$ 值。"},
    {'id': 22, 'category': '高等数学', 'content': r"求二元函数 $f(x, y) = x^2 + y^2$ 的梯度向量在点 $(1, 2)$ 的值。"},
    {'id': 23, 'category': '高等数学', 'content': r"计算二重积分 $\iint_D (x + y) dxdy$，区域 $D$ 为 $0 \leq x \leq 1, 0 \leq y \leq 1$。"},
    {'id': 24, 'category': '高等数学', 'content': r"写出函数 $f(x) = \cos x$ 在 $x=0$ 处的泰勒级数展开式的前三项。"},
    {'id': 25, 'category': '高等数学', 'content': r"求函数 $f(x, y) = x^2y + \sin(xy)$ 对 $x$ 的偏导数。"},
    {'id': 26, 'category': '高等数学', 'content': r"计算由曲线 $y = x$ 和 $y = x^2$ 所围成图形的面积。"},
    {'id': 27, 'category': '高等数学', 'content': r"求二阶常系数齐次线性微分方程 $y'' - 4y = 0$ 的通解。"},
    {'id': 28, 'category': '高等数学', 'content': r"计算三元函数 $f(x, y, z) = xyz$ 的梯度向量在点 $(1, 1, 1)$ 处的值。"},
    {'id': 29, 'category': '高等数学', 'content': r"计算三重积分 $\iiint_V dV$，其中 $V$ 是单位球体 $x^2 + y^2 + z^2 \leq 1$。"},
    {'id': 30, 'category': '高等数学', 'content': r"求函数 $f(x) = \ln(1+x)$ 的定义域。"},
    {'id': 31, 'category': '高等数学', 'content': r"计算参数方程 $x = \cos t, y = \sin t$ 在 $t = \pi/4$ 处的斜率。"},
    {'id': 32, 'category': '高等数学', 'content': r"利用分部积分法计算 $\int \ln x dx$。"},
    {'id': 33, 'category': '高等数学', 'content': r"求极限 $\lim_{x \to 0} \frac{1 - \cos x}{x^2}$。"},
    {'id': 34, 'category': '高等数学', 'content': r"计算广义积分 $\int_{1}^{\infty} \frac{1}{x^2} dx$。"},
    {'id': 35, 'category': '高等数学', 'content': r"求曲线 $y = \ln x$ 在点 $(e, 1)$ 处的法线方程。"},
    {'id': 36, 'category': '高等数学', 'content': r"设 $z = e^{x-2y}$，求 $\frac{\partial z}{\partial x}$ 和 $\frac{\partial z}{\partial y}$。"},
    {'id': 37, 'category': '高等数学', 'content': r"求全微分 $dz = x dx + y dy$ 的原函数 $z(x, y)$。"},
    {'id': 38, 'category': '高等数学', 'content': r"利用格林公式计算闭曲线积分 $\oint_L (x^2 - y^2) dx + 2xy dy$，其中 $L$ 为单位圆。"},
    {'id': 39, 'category': '高等数学', 'content': r"判断常数项级数 $\sum_{n=1}^{\infty} \frac{(-1)^n}{n}$ 是否绝对收敛。"},
    {'id': 40, 'category': '高等数学', 'content': r"求幂级数 $\sum_{n=1}^{\infty} \frac{x^n}{n}$ 的收敛半径。"},
    {'id': 41, 'category': '高等数学', 'content': r"计算不定积分 $\int \frac{1}{1+x^2} dx$。"},
    {'id': 42, 'category': '高等数学', 'content': r"求微分方程 $y' = x y$ 的通解。"},
    {'id': 43, 'category': '高等数学', 'content': r"求抛物面 $z = x^2 + y^2$ 在点 $(1, 1, 2)$ 处的切平面方程。"},
    {'id': 44, 'category': '高等数学', 'content': r"设 $u = \sin(xy)$，求 $\frac{\partial^2 u}{\partial x \partial y}$。"},
    {'id': 45, 'category': '高等数学', 'content': r"计算曲线积分 $\int_C (x+y) ds$，$C$ 为连接 $(0,0)$ 与 $(1,1)$ 的直线段。"},
    {'id': 46, 'category': '高等数学', 'content': r"求极限 $\lim_{n \to \infty} \sqrt[n]{n}$。"},
    {'id': 47, 'category': '高等数学', 'content': r"证明函数 $f(x) = \sin x$ 在区间 $(-\infty, +\infty)$ 上一致连续。"},
    {'id': 48, 'category': '高等数学', 'content': r"利用牛顿-莱布尼茨公式证明 $\int_{-a}^{a} f(x) dx = 0$ ($f(x)$ 为奇函数)。"},
    {'id': 49, 'category': '高等数学', 'content': r"求空间曲面 $x^2 + y^2 + z^2 = 3$ 在点 $(1,1,1)$ 处的法向量。"},
    {'id': 50, 'category': '高等数学', 'content': r"计算二重积分 $\iint_D e^{-x^2-y^2} dxdy$，$D$ 为全平面（极坐标变换）。"},
    {'id': 51, 'category': '高等数学', 'content': r"利用分部积分法计算定积分 $\int_0^1 x e^x dx$。"},
    {'id': 52, 'category': '高等数学', 'content': r"计算二重积分 $\iint_D (x^2+y^2) dxdy$，其中 $D$ 是以原点为中心、半径为 $R$ 的圆的上半部分。"},
    {'id': 53, 'category': '高等数学', 'content': r"判断常数项级数 $\sum_{n=1}^{\infty} \frac{\sin n}{n^2}$ 的绝对收敛性。"},
    {'id': 54, 'category': '高等数学', 'content': r"求曲面 $z = xy$ 在点 $(1, 2, 2)$ 处的切平面方程。"},
    {'id': 55, 'category': '高等数学', 'content': r"利用泰勒公式，写出 $\sin x$ 在 $x=0$ 处的带有佩亚诺余项的 3 阶展开式。"},
    {'id': 56, 'category': '高等数学', 'content': r"计算含有参数的积分 $\int \frac{dx}{x^2 + a^2}$ (假设 $a > 0$)。"},
    {'id': 57, 'category': '高等数学', 'content': r"已知函数 $y = x^x$，利用对数求导法求其导数 $y'$。"},
    {'id': 58, 'category': '高等数学', 'content': r"讨论反常积分 $\int_1^{+\infty} \frac{dx}{x^p}$ 收敛的 $p$ 的取值范围。"},
    {'id': 59, 'category': '高等数学', 'content': r"计算第一类曲线积分 $\int_L (x^2+y^2) ds$，其中 $L$ 为圆周 $x^2+y^2=a^2$。"},
    {'id': 60, 'category': '高等数学', 'content': r"求解一阶线性常微分方程 $y' + \frac{1}{x}y = \sin x$ 的通解。"},

    # ==================== 线性代数 (60题) ====================
    {'id': 61, 'category': '线性代数', 'content': r"计算行列式 $|A|$ 的值，其中 $A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$。"},
    {'id': 62, 'category': '线性代数', 'content': r"计算矩阵 $A = \begin{pmatrix} 1 & 1 \\ 0 & 1 \end{pmatrix}$ 的逆矩阵。"},
    {'id': 63, 'category': '线性代数', 'content': r"计算矩阵 $A = \begin{pmatrix} 2 & 0 \\ 0 & 3 \end{pmatrix}$ 的特征值。"},
    {'id': 64, 'category': '线性代数', 'content': r"求向量组 $\mathbf{a}_1=(1,0), \mathbf{a}_2=(0,1)$ 生成的向量空间维数。"},
    {'id': 65, 'category': '线性代数', 'content': r"计算向量 $\mathbf{a}=(1, 2, 3)$ 和 $\mathbf{b}=(4, 5, 6)$ 的点积。"},
    {'id': 66, 'category': '线性代数', 'content': r"计算向量 $\mathbf{a}=(1, 0, 0)$ 和 $\mathbf{b}=(0, 1, 0)$ 的叉积向量。"},
    {'id': 67, 'category': '线性代数', 'content': r"计算矩阵 $A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix}$ 的秩。"},
    {'id': 68, 'category': '线性代数', 'content': r"求二次型 $f(x, y) = x^2 + 2xy + y^2$ 的标准型。"},
    {'id': 69, 'category': '线性代数', 'content': r"已知正交矩阵 $A$，若 $|A| > 0$，求 $|A|$ 的值。"},
    {'id': 70, 'category': '线性代数', 'content': r"解线性方程组：$x + y = 3, x - y = 1$，求 $x$ 和 $y$ 的值。"},
    {'id': 71, 'category': '线性代数', 'content': r"已知矩阵 $A = \text{diag}(1, 2, 3)$，求其逆矩阵 $A^{-1}$。"},
    {'id': 72, 'category': '线性代数', 'content': r"若 3阶矩阵 $A$ 的特征值为 1, 2, 3，求矩阵的行列式 $|A|$。"},
    {'id': 73, 'category': '线性代数', 'content': r"判断向量 $\mathbf{v}_1 = (1, 2)$ 与 $\mathbf{v}_2 = (-2, 1)$ 是否正交。"},
    {'id': 74, 'category': '线性代数', 'content': r"计算矩阵 $A = \begin{pmatrix} 1 & 0 \\ 2 & 1 \end{pmatrix}$ 的平方 $A^2$。"},
    {'id': 75, 'category': '线性代数', 'content': r"求矩阵 $A = \begin{pmatrix} 1 & 2 \\ 2 & 4 \end{pmatrix}$ 的迹 (Trace)。"},
    {'id': 76, 'category': '线性代数', 'content': r"已知 $\mathbf{a} = (1, 1)$，求 $\mathbf{a}$ 在 $\mathbf{b} = (1, 0)$ 上的投影向量。"},
    {'id': 77, 'category': '线性代数', 'content': r"若 3x3 矩阵 $A$ 的秩为 2，问齐次线性方程组 $A\mathbf{x} = \mathbf{0}$ 的基础解系维数。"},
    {'id': 78, 'category': '线性代数', 'content': r"计算 $n$ 阶单位矩阵 $I_n$ 的行列式值。"},
    {'id': 79, 'category': '线性代数', 'content': r"求矩阵 $A = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}$ 的特征向量。"},
    {'id': 80, 'category': '线性代数', 'content': r"已知矩阵 $A, B$ 为 $n$ 阶方阵，写出 $(AB)^T$ 的展开式。"},
    {'id': 81, 'category': '线性代数', 'content': r"设 $A$ 是 $m \times n$ 矩阵，若 $A\mathbf{x} = \mathbf{0}$ 只有零解，求 $A$ 的列向量组的线性相关性。"},
    {'id': 82, 'category': '线性代数', 'content': r"计算三阶范德蒙行列式 $V(1, 2, 3)$ 的值。"},
    {'id': 83, 'category': '线性代数', 'content': r"设 $\alpha, \beta$ 为 $n$ 维列向量，证明矩阵 $I - \alpha\beta^T$ 可逆的条件是 $\beta^T\alpha \neq 1$。"},
    {'id': 84, 'category': '线性代数', 'content': r"若矩阵 $A$ 与 $B$ 相似，它们必定有相同的什么多项式？"},
    {'id': 85, 'category': '线性代数', 'content': r"求实对称矩阵 $A$ 的不同特征值对应的特征向量之间的内积。"},
    {'id': 86, 'category': '线性代数', 'content': r"将向量 $\mathbf{a}=(1, -1, 1)^T$ 扩展为 $\mathbb{R}^3$ 的一组正交基。"},
    {'id': 87, 'category': '线性代数', 'content': r"已知矩阵 $A$ 满足 $A^2 = A$，且 $A \neq I, A \neq 0$，求 $A$ 的特征值。"},
    {'id': 88, 'category': '线性代数', 'content': r"写出将二次型 $f(x,y)=2xy$ 化为标准型的正交变换矩阵。"},
    {'id': 89, 'category': '线性代数', 'content': r"设 $A$ 为 3 阶方阵，且 $|A|=2$，求 $|2A^{-1}|$ 的值。"},
    {'id': 90, 'category': '线性代数', 'content': r"判断二次型 $f(x_1,x_2) = x_1^2 + 4x_1x_2 + 5x_2^2$ 的正定性。"},
    {'id': 91, 'category': '线性代数', 'content': r"设向量组 $\alpha_1, \alpha_2$ 线性无关，判断 $\alpha_1+\alpha_2$ 与 $\alpha_1-\alpha_2$ 的线性相关性。"},
    {'id': 92, 'category': '线性代数', 'content': r"矩阵 $A$ 的秩为 $r$，其伴随矩阵 $A^*$ 的秩在 $r=n-1$ 时是多少？"},
    {'id': 93, 'category': '线性代数', 'content': r"已知 $A\mathbf{x} = \mathbf{b}$ 有无穷多解，推断导出矩阵 $(A|\mathbf{b})$ 的秩与方程个数的关系。"},
    {'id': 94, 'category': '线性代数', 'content': r"求矩阵 $A = \begin{pmatrix} 1 & 2 \\ 2 & 1 \end{pmatrix}$ 对应二次型的矩阵。"},
    {'id': 95, 'category': '线性代数', 'content': r"若 $A, B$ 皆为反对称矩阵，判断 $A+B$ 是否仍为反对称矩阵。"},
    {'id': 96, 'category': '线性代数', 'content': r"计算向量组 $(1,0,0), (0,2,0), (0,0,3)$ 所构成的平行六面体的体积。"},
    {'id': 97, 'category': '线性代数', 'content': r"设矩阵 $A$ 的特征多项式为 $f(\lambda) = \lambda^3 - 2\lambda^2 + \lambda$，求 $A$ 的特征值。"},
    {'id': 98, 'category': '线性代数', 'content': r"已知 $A$ 为三阶上三角矩阵，主对角线元素为 $1, 2, -1$，求 $|A|$。"},
    {'id': 99, 'category': '线性代数', 'content': r"施密特正交化过程中，求第二个正交向量 $\beta_2$ 的公式表达式。"},
    {'id': 100, 'category': '线性代数', 'content': r"若矩阵 $A$ 满足 $A^T A = I$，则称 $A$ 是什么矩阵？"},
    {'id': 101, 'category': '线性代数', 'content': r"设 $A$ 是 $n$ 阶奇异矩阵，证明零是 $A$ 的一个特征值。"},
    {'id': 102, 'category': '线性代数', 'content': r"写出克莱姆法则 (Cramer's Rule) 中求解 $x_i$ 的公式。"},
    {'id': 103, 'category': '线性代数', 'content': r"如果矩阵 $A$ 可逆，证明 $(A^{-1})^T = (A^T)^{-1}$。"},
    {'id': 104, 'category': '线性代数', 'content': r"设 $A$ 为 4 阶方阵，秩为 3，求基础解系包含的向量个数。"},
    {'id': 105, 'category': '线性代数', 'content': r"证明矩阵的迹 (Trace) 等于其所有特征值之和。"},
    {'id': 106, 'category': '线性代数', 'content': r"对于初等矩阵 $E_{12}(k)$（第一行加上第二行的$k$倍），求其逆矩阵。"},
    {'id': 107, 'category': '线性代数', 'content': r"设向量空间 $V$ 的基为 $\mathbf{e}_1, \mathbf{e}_2$，写出向量 $\mathbf{x} = 2\mathbf{e}_1 - 3\mathbf{e}_2$ 在此基下的坐标。"},
    {'id': 108, 'category': '线性代数', 'content': r"正定矩阵的主子式必须满足什么条件？"},
    {'id': 109, 'category': '线性代数', 'content': r"已知矩阵 $A$ 可以对角化，说明 $A$ 必须具备什么条件？"},
    {'id': 110, 'category': '线性代数', 'content': r"计算矩阵方程 $AX = B$ 的解 $X$（假设 $A$ 可逆）。"},
    {'id': 111, 'category': '线性代数', 'content': r"若 $n$ 阶方阵 $A$ 满足 $A^3 = O$，证明矩阵 $I - A$ 可逆。"},
    {'id': 112, 'category': '线性代数', 'content': r"设 $\alpha_1, \alpha_2, \alpha_3$ 是三维列向量，若行列式 $|\alpha_1, \alpha_2, \alpha_3| = 2$，求 $|2\alpha_1, -\alpha_2, \alpha_3+\alpha_1|$ 的值。"},
    {'id': 113, 'category': '线性代数', 'content': r"已知二阶实对称矩阵的特征值为 1 和 -1，求其行列式的值。"},
    {'id': 114, 'category': '线性代数', 'content': r"已知 $\mathbf{x}^T A \mathbf{x}$ 是正定二次型，证明矩阵 $A$ 的主对角线元素必须全为正数。"},
    {'id': 115, 'category': '线性代数', 'content': r"求矩阵 $A = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}$ 的正交相似对角化矩阵。"},
    {'id': 116, 'category': '线性代数', 'content': r"向量组线性无关的充要条件是其矩阵的秩等于什么？"},
    {'id': 117, 'category': '线性代数', 'content': r"设 $A, B$ 是同阶正交矩阵，证明 $AB$ 也是正交矩阵。"},
    {'id': 118, 'category': '线性代数', 'content': r"如果向量 $\mathbf{x}$ 是方阵 $A$ 属于特征值 $\lambda$ 的特征向量，求矩阵 $A^2 + 2A + I$ 的对应特征值。"},
    {'id': 119, 'category': '线性代数', 'content': r"求解齐次线性方程组 $A\mathbf{x}=\mathbf{0}$ 只有零解的充要条件是什么？"},
    {'id': 120, 'category': '线性代数', 'content': r"若方阵 $A$ 的所有列向量之和为零向量，推断 0 是否为 $A$ 的特征值。"},

    # ==================== 概率统计 (60题) ====================
    {'id': 121, 'category': '概率统计', 'content': r"投掷一枚均匀硬币 3 次，计算恰好出现 2 次正面的概率值。"},
    {'id': 122, 'category': '概率统计', 'content': r"设 $X \sim N(0, 1)$，求 $E(X^2)$ 的值。"},
    {'id': 123, 'category': '概率统计', 'content': r"已知 $P(A)=0.5, P(B)=0.4$，$A$ 和 $B$ 独立，计算 $P(A \cap B)$。"},
    {'id': 124, 'category': '概率统计', 'content': r"一盒中有 3 红 2 白球，不放回取 2 次，计算第二次取到红球的概率。"},
    {'id': 125, 'category': '概率统计', 'content': r"计算数据集 $\{1, 2, 3, 4, 5\}$ 的样本方差值。"},
    {'id': 126, 'category': '概率统计', 'content': r"若 $X$ 服从参数为 $\lambda$ 的泊松分布，求 $E(X)$。"},
    {'id': 127, 'category': '概率统计', 'content': r"若 $X$ 服从参数为 $\lambda$ 的指数分布，求 $P(X > 1/\lambda)$。"},
    {'id': 128, 'category': '概率统计', 'content': r"计算掷两个均匀骰子点数之和为 7 的概率。"},
    {'id': 129, 'category': '概率统计', 'content': r"若 $X, Y$ 独立且均服从 $U(0,1)$，求 $E(X+Y)$ 的值。"},
    {'id': 130, 'category': '概率统计', 'content': r"已知 $P(B|A)=0.8, P(A)=0.5, P(B)=0.6$，计算 $P(A|B)$ 的值。"},
    {'id': 131, 'category': '概率统计', 'content': r"设 $X \sim B(10, 0.5)$，求随机变量 $X$ 的数学期望 $E(X)$。"},
    {'id': 132, 'category': '概率统计', 'content': r"已知 $P(A) = 0.3, P(B) = 0.4$，若 $A, B$ 互斥，求 $P(A \cup B)$。"},
    {'id': 133, 'category': '概率统计', 'content': r"计算标准正态分布密度函数在 $x=0$ 处的值。"},
    {'id': 134, 'category': '概率统计', 'content': r"设 $X, Y$ 独立且方差分别为 1 和 2，求 $D(X-Y)$。"},
    {'id': 135, 'category': '概率统计', 'content': r"若随机变量 $X$ 只有两个等概率取值，计算其信息熵 $H(X)$ (bit)。"},
    {'id': 136, 'category': '概率统计', 'content': r"求数据组 $\{2, 4, 4, 4, 5, 5, 7, 9\}$ 的众数。"},
    {'id': 137, 'category': '概率统计', 'content': r"若 $X$ 服从参数为 2 的指数分布，写出 $x > 0$ 时的概率密度函数表达式。"},
    {'id': 138, 'category': '概率统计', 'content': r"计算随机变量 $X \sim U(0, 10)$ 落在区间 $[2, 5]$ 的概率。"},
    {'id': 139, 'category': '概率统计', 'content': r"已知 $E(X)=2, D(X)=4$，计算 $E(X^2)$。"},
    {'id': 140, 'category': '概率统计', 'content': r"写出切比雪夫不等式中用于估计概率界限的公式。"},
    {'id': 141, 'category': '概率统计', 'content': r"袋中有 5 个正品 2 个次品，任取 3 个，求全为正品的概率。"},
    {'id': 142, 'category': '概率统计', 'content': r"若 $X \sim N(\mu, \sigma^2)$，计算 $P(X < \mu)$ 的值。"},
    {'id': 143, 'category': '概率统计', 'content': r"写出全概率公式的数学表达式。"},
    {'id': 144, 'category': '概率统计', 'content': r"写出贝叶斯公式的数学表达式。"},
    {'id': 145, 'category': '概率统计', 'content': r"二项分布在 $n$ 很大，$p$ 很小时，可以用什么分布来近似？"},
    {'id': 146, 'category': '概率统计', 'content': r"求连续型随机变量密度函数 $f(x)$ 满足的归一化条件。"},
    {'id': 147, 'category': '概率统计', 'content': r"若 $X \sim N(1, 4)$，将其标准化为 $Z \sim N(0, 1)$ 的变换公式是什么？"},
    {'id': 148, 'category': '概率统计', 'content': r"设 $X, Y$ 独立，证明协方差 $\text{Cov}(X, Y) = 0$。"},
    {'id': 149, 'category': '概率统计', 'content': r"相关系数 $\rho_{XY} = \pm 1$ 意味着 $X$ 和 $Y$ 之间存在什么关系？"},
    {'id': 150, 'category': '概率统计', 'content': r"写出大数定律（如弱大数定律）的直观物理意义。"},
    {'id': 151, 'category': '概率统计', 'content': r"在假设检验中，第一类错误（弃真错误）的概率通常用什么字母表示？"},
    {'id': 152, 'category': '概率统计', 'content': r"正态总体均值 $\mu$ 未知时，用样本方差构造的检验统计量服从什么分布？"},
    {'id': 153, 'category': '概率统计', 'content': r"写出卡方分布 $\chi^2(n)$ 的数学期望与自由度 $n$ 的关系。"},
    {'id': 154, 'category': '概率统计', 'content': r"对于二维随机向量 $(X, Y)$，写出边缘概率密度 $f_X(x)$ 的积分表达式。"},
    {'id': 155, 'category': '概率统计', 'content': r"最大似然估计法的基本思想是什么？"},
    {'id': 156, 'category': '概率统计', 'content': r"若估计量 $\hat{\theta}$ 的数学期望等于未知参数 $\theta$，则称该估计量具备什么性质？"},
    {'id': 157, 'category': '概率统计', 'content': r"区间估计中，置信度 $1 - \alpha$ 反映了估计的什么特性？"},
    {'id': 158, 'category': '概率统计', 'content': r"两两独立的三个事件，是否一定相互独立？"},
    {'id': 159, 'category': '概率统计', 'content': r"投掷一枚硬币直至出现正面，记录投掷次数 $X$，问 $X$ 服从什么分布？"},
    {'id': 160, 'category': '概率统计', 'content': r"写出泊松分布中参数 $\lambda$ 的统计学意义。"},
    {'id': 161, 'category': '概率统计', 'content': r"设 $X \sim N(\mu, \sigma^2)$，其概率密度曲线的拐点横坐标是多少？"},
    {'id': 162, 'category': '概率统计', 'content': r"对于任意随机变量 $X$，其分布函数 $F(x)$ 是左连续还是右连续的？"},
    {'id': 163, 'category': '概率统计', 'content': r"若 $X, Y$ 同分布，是否意味着 $P(X=Y) = 1$？"},
    {'id': 164, 'category': '概率统计', 'content': r"中心极限定理说明，大量独立随机变量之和近似服从什么分布？"},
    {'id': 165, 'category': '概率统计', 'content': r"样本均值 $\bar{X}$ 是总体均值 $\mu$ 的一致估计量吗？"},
    {'id': 166, 'category': '概率统计', 'content': r"设总体矩为 $\mu_k$，样本矩为 $A_k$，矩估计法的核心原理是什么？"},
    {'id': 167, 'category': '概率统计', 'content': r"显著性水平 $\alpha=0.05$ 表示拒绝域在概率密度曲线下占多大面积？"},
    {'id': 168, 'category': '概率统计', 'content': r"线性回归模型 $Y = \beta_0 + \beta_1 X + \varepsilon$ 中，误差项 $\varepsilon$ 通常假设服从什么分布？"},
    {'id': 169, 'category': '概率统计', 'content': r"方差分析 (ANOVA) 主要用于检验多个总体的什么参数是否相等？"},
    {'id': 170, 'category': '概率统计', 'content': r"给出 $P(A|B)$ 与 $P(A \cap B)$ 及 $P(B)$ 之间的基本关系式。"},
    {'id': 171, 'category': '概率统计', 'content': r"设随机变量 $X \sim N(0, 1)$，求 $Y = e^X$ 的数学期望（对数正态分布均值）。"},
    {'id': 172, 'category': '概率统计', 'content': r"已知事件 $A, B$ 相互独立，且 $P(A \cup B) = 0.8, P(A) = 0.5$，求 $P(B)$。"},
    {'id': 173, 'category': '概率统计', 'content': r"无偏样本方差 $S^2$ 的公式分母为什么要除以 $n-1$ 而不是 $n$？"},
    {'id': 174, 'category': '概率统计', 'content': r"已知总体 $X \sim U(0, \theta)$，求未知参数 $\theta$ 的一阶矩估计。"},
    {'id': 175, 'category': '概率统计', 'content': r"在假设检验中，什么是“弃真”错误和“存伪”错误？"},
    {'id': 176, 'category': '概率统计', 'content': r"设随机变量 $X \sim \chi^2(n)$，求其方差 $D(X)$ 与自由度的关系。"},
    {'id': 177, 'category': '概率统计', 'content': r"若 $X, Y$ 独立，且分别服从泊松分布 $P(\lambda_1)$ 和 $P(\lambda_2)$，问 $X+Y$ 服从什么分布？"},
    {'id': 178, 'category': '概率统计', 'content': r"简述大数定律和中心极限定理在统计学应用上的核心区别。"},
    {'id': 179, 'category': '概率统计', 'content': r"在置信水平 $1-\alpha$ 下，正态总体均值的双侧置信区间长度与样本容量 $n$ 呈什么关系？"},
    {'id': 180, 'category': '概率统计', 'content': r"解释协方差 $\text{Cov}(X,Y)$ 为正、负、零时，分别代表两个变量具有什么线性相关性。"},

    # ==================== C语言 (60题) ====================
    {'id': 181, 'category': 'C语言', 'content': r"在C语言中，`int` 类型在 32 位系统中通常占用几个字节？"},
    {'id': 182, 'category': 'C语言', 'content': r"解释 `#include <stdio.h>` 中尖括号 `< >` 和双引号 `\" \"` 的区别。"},
    {'id': 183, 'category': 'C语言', 'content': r"写出表达式 `5 / 2` 在C语言中的计算结果。"},
    {'id': 184, 'category': 'C语言', 'content': r"如何定义一个整型常量 `MAX_SIZE` 值为 100？请写出宏定义代码。"},
    {'id': 185, 'category': 'C语言', 'content': r"分析代码 `int a=1; int b=a++;` 执行后，`a` 和 `b` 的值分别是多少？"},
    {'id': 186, 'category': 'C语言', 'content': r"在 `switch` 语句中，`break` 关键字的作用是什么？"},
    {'id': 187, 'category': 'C语言', 'content': r"写一个 `for` 循环的头部，使其实现无限死循环。"},
    {'id': 188, 'category': 'C语言', 'content': r"定义一个长度为 10 的整型数组 `arr`，并将其所有元素初始化为 0。"},
    {'id': 189, 'category': 'C语言', 'content': r"数组名（如 `arr`）在表达式中通常退化为什么？"},
    {'id': 190, 'category': 'C语言', 'content': r"已知 `int arr[5];`，写出访问数组最后一个元素的表达式。"},
    {'id': 191, 'category': 'C语言', 'content': r"什么是指针？请简要描述指针变量存储的内容。"},
    {'id': 192, 'category': 'C语言', 'content': r"已知 `int x = 10; int *p = &x;`，如何通过指针 `p` 将 `x` 的值修改为 20？"},
    {'id': 193, 'category': 'C语言', 'content': r"在C语言中，`NULL` 指针的典型用途是什么？"},
    {'id': 194, 'category': 'C语言', 'content': r"简述按值传递和按指针传递在函数调用时的区别。"},
    {'id': 195, 'category': 'C语言', 'content': r"写出声明一个函数指针 `fp` 的代码，该函数接收两个 `int` 参数并返回 `int`。"},
    {'id': 196, 'category': 'C语言', 'content': r"字符串在C语言中是如何表示和结尾的？"},
    {'id': 197, 'category': 'C语言', 'content': r"函数 `strlen(\"Hello\")` 和 `sizeof(\"Hello\")` 的返回值分别是多少？"},
    {'id': 198, 'category': 'C语言', 'content': r"如何使用标准库函数将字符串 `src` 复制到字符串 `dest` 中？"},
    {'id': 199, 'category': 'C语言', 'content': r"结构体（`struct`）和联合体（`union`）在内存分配上的根本区别是什么？"},
    {'id': 200, 'category': 'C语言', 'content': r"已知结构体指针 `struct Student *s`，如何访问其成员 `age`？"},
    {'id': 201, 'category': 'C语言', 'content': r"`malloc` 和 `calloc` 在动态分配内存时，最大的不同点是什么？"},
    {'id': 202, 'category': 'C语言', 'content': r"动态分配的内存使用完毕后，必须调用哪个函数释放？如果不释放会怎样？"},
    {'id': 203, 'category': 'C语言', 'content': r"分析代码：`int *p = malloc(sizeof(int)); free(p); p = NULL;` 最后一步的作用是什么？"},
    {'id': 204, 'category': 'C语言', 'content': r"宏定义 `#define SQUARE(x) x*x` 存在什么隐患？如果计算 `SQUARE(1+2)` 结果是多少？"},
    {'id': 205, 'category': 'C语言', 'content': r"条件编译指令 `#ifndef` 和 `#define` 常常组合在一起用于解决什么问题？"},
    {'id': 206, 'category': 'C语言', 'content': r"在多文件编程中，关键字 `extern` 的作用是什么？"},
    {'id': 207, 'category': 'C语言', 'content': r"关键字 `static` 修饰局部变量时，会改变该变量的生命周期还是作用域？"},
    {'id': 208, 'category': 'C语言', 'content': r"简述关键字 `volatile` 在嵌入式编程中的典型作用。"},
    {'id': 209, 'category': 'C语言', 'content': r"如何打开一个名为 `data.txt` 的文本文件用于追加写入？写出 `fopen` 语句。"},
    {'id': 210, 'category': 'C语言', 'content': r"函数 `feof()` 在文件操作中起什么作用？"},
    {'id': 211, 'category': 'C语言', 'content': r"二进制文件读写通常使用哪两个标准库函数？"},
    {'id': 212, 'category': 'C语言', 'content': r"位运算符 `&` 和逻辑运算符 `&&` 有什么区别？"},
    {'id': 213, 'category': 'C语言', 'content': r"将变量 `unsigned char flags` 的第 3 位（从 0 开始）置为 1，写出位运算表达式。"},
    {'id': 214, 'category': 'C语言', 'content': r"将变量 `unsigned char flags` 的第 2 位清零，其他位不变，写出位运算表达式。"},
    {'id': 215, 'category': 'C语言', 'content': r"什么是递归函数？递归函数必须具备的两个基本要素是什么？"},
    {'id': 216, 'category': 'C语言', 'content': r"在控制台输出带有两位小数的浮点数 `f`，`printf` 的格式控制符应该怎么写？"},
    {'id': 217, 'category': 'C语言', 'content': r"`scanf(\"%s\", str);` 在读取用户输入的字符串时，遇到什么字符会停止读取？"},
    {'id': 218, 'category': 'C语言', 'content': r"指针数组和数组指针的区别是什么？请分别给出一个定义示例。"},
    {'id': 219, 'category': 'C语言', 'content': r"解释什么是“野指针”，并给出一个避免产生野指针的良好编程习惯。"},
    {'id': 220, 'category': 'C语言', 'content': r"代码 `char *s = \"hello\"; s[0] = 'H';` 运行时会发生什么问题？为什么？"},
    {'id': 221, 'category': 'C语言', 'content': r"如何计算任意类型数组 `arr` 的元素个数？写出利用 `sizeof` 的表达式。"},
    {'id': 222, 'category': 'C语言', 'content': r"什么是枚举类型（`enum`）？它主要用来替代什么机制？"},
    {'id': 223, 'category': 'C语言', 'content': r"`typedef` 关键字的作用是什么？举一个为 `unsigned int` 取别名的例子。"},
    {'id': 224, 'category': 'C语言', 'content': r"局部变量、全局变量、动态分配的内存分别存放在进程空间的哪个区域？"},
    {'id': 225, 'category': 'C语言', 'content': r"如何通过命令行参数传递数据给C程序？请写出 `main` 函数带参的签名。"},
    {'id': 226, 'category': 'C语言', 'content': r"在嵌套循环中，`goto` 语句的一个合理且常见的应用场景是什么？"},
    {'id': 227, 'category': 'C语言', 'content': r"标准库 `<stdlib.h>` 中的 `qsort` 比较函数的返回值类型必须是什么？"},
    {'id': 228, 'category': 'C语言', 'content': r"什么是字节对齐（Byte Alignment）？在结构体中它会造成什么影响？"},
    {'id': 229, 'category': 'C语言', 'content': r"已知 `int a[5] = {1,2,3,4,5}; int *p = (int *)(&a + 1);`，求 `*(p-1)` 的值。"},
    {'id': 230, 'category': 'C语言', 'content': r"如何判断系统的端序（大端序 / 小端序）？简述用C语言代码验证的思路。"},
    {'id': 231, 'category': 'C语言', 'content': r"解释 C 语言中 `const int *p` 和 `int * const p` 的区别。"},
    {'id': 232, 'category': 'C语言', 'content': r"`sizeof` 和 `strlen` 在处理包含 `\0` 的字符数组时有什么不同？"},
    {'id': 233, 'category': 'C语言', 'content': r"什么是内存泄漏（Memory Leak）？在 C 语言编程中如何避免？"},
    {'id': 234, 'category': 'C语言', 'content': r"在 C 语言中，如何实现一个通用交换宏 `#define SWAP(a, b)`？"},
    {'id': 235, 'category': 'C语言', 'content': r"`sprintf` 和 `snprintf` 函数有什么区别？为什么更推荐使用后者？"},
    {'id': 236, 'category': 'C语言', 'content': r"函数指针数组的应用场景有哪些？试举一例说明。"},
    {'id': 237, 'category': 'C语言', 'content': r"结构体内存对齐的原则是什么？简述其对程序运行效率和内存占用的影响。"},
    {'id': 238, 'category': 'C语言', 'content': r"`static` 关键字在修饰全局变量和局部变量时的作用域和生命周期有何不同？"},
    {'id': 239, 'category': 'C语言', 'content': r"解释 C 语言系统环境中的大端模式（Big-endian）和小端模式（Little-endian）。"},
    {'id': 240, 'category': 'C语言', 'content': r"如何用 C 语言中标准库函数计算一个以二进制追加模式打开的文件的字节大小？"}
]