QUESTION_BANK = [
    {'id': 1, 'category': '高等数学', 'content': '求函数 \( f(x) = x^3 - 3x + 1 \) 的极大值点。'},
    {'id': 2, 'category': '高等数学', 'content': '计算不定积分 \( \int x \cdot e^x dx \)。'},
    {'id': 3, 'category': '高等数学', 'content': '求极限 \( \lim_{x \to 0} \frac{\sin(x)}{x} \)。'},
    {'id': 4, 'category': '高等数学', 'content': '已知 \( y = \ln(\tan(x)) \)，求 \( dy/dx \)。'},
    {'id': 5, 'category': '高等数学', 'content': '计算定积分 \( \int_{0}^{\pi} \sin(x) dx \)。'},
    {'id': 6, 'category': '高等数学', 'content': '求曲线 \( y = x^2 \) 在 \( x = 1 \) 处的切线方程。'},
    {'id': 7, 'category': '高等数学', 'content': '求级数 \( \sum_{n=1}^{\infty} \frac{1}{2^n} \) 的和。'},
    {'id': 8, 'category': '高等数学', 'content': '求函数 \( f(x, y) = x^2 + y^2 \) 的梯度向量 \( \text{grad}(f) \) 在点 \( (1, 2) \) 的值。'},
    {'id': 9, 'category': '高等数学', 'content': '计算二重积分 \( \iint_D (x + y) dxdy \)，区域 \( D \) 为 \( 0 \leq x \leq 1, 0 \leq y \leq 1 \)。'},
    {'id': 10, 'category': '高等数学', 'content': '求微分方程 \( y\' + y = 0 \) 满足初值 \( y(0)=1 \) 的特解。'},
    {'id': 11, 'category': '高等数学', 'content': '求函数 \( f(x) = x \cdot |x| \) 的导函数 \( f\'(x) \)。'},
    {'id': 12, 'category': '高等数学', 'content': '利用洛必达法则计算 \( \lim_{x \to \infty} \frac{\ln(x)}{x} \)。'},
    {'id': 13, 'category': '高等数学', 'content': '写出函数 \( f(x) = e^x \) 的麦克劳林级数的前三项。'},
    {'id': 14, 'category': '高等数学', 'content': '计算圆 \( x^2 + y^2 = 4 \) 围成的面积值。'},
    {'id': 15, 'category': '高等数学', 'content': '计算曲线 \( y=x^2 \) 从 \( x=0 \) 到 \( x=1 \) 的弧长积分表达式。'},
    {'id': 16, 'category': '高等数学', 'content': '求 \( z = x^2 - y^2 \) 在点 \( (0,0) \) 处的黑塞矩阵 (Hessian Matrix)。'},
    {'id': 17, 'category': '高等数学', 'content': '计算向量场 \( \mathbf{F} = (y, -x) \) 的散度数值。'},
    {'id': 18, 'category': '高等数学', 'content': '计算向量场 \( \mathbf{F} = (y, -x, 0) \) 的旋度向量。'},
    {'id': 19, 'category': '高等数学', 'content': '求微分方程 \( y\'\' + y = 0 \) 满足 \( y(0)=0, y\'(0)=1 \) 的特解。'},
    {'id': 20, 'category': '高等数学', 'content': '求函数 \( f(x) = x^2 \) 在区间 \( [0, 2] \) 上满足拉格朗日中值定理的 \( \xi \) 值。'},
    {'id': 21, 'category': '线性代数', 'content': '计算行列式 \( |A| \) 的值，其中 \( A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} \)。'},
    {'id': 22, 'category': '线性代数', 'content': '计算矩阵 \( A = \begin{pmatrix} 1 & 1 \\ 0 & 1 \end{pmatrix} \) 的逆矩阵。'},
    {'id': 23, 'category': '线性代数', 'content': '计算矩阵 \( A = \begin{pmatrix} 2 & 0 \\ 0 & 3 \end{pmatrix} \) 的特征值。'},
    {'id': 24, 'category': '线性代数', 'content': '求向量组 \( \mathbf{a}_1=(1,0), \mathbf{a}_2=(0,1) \) 生成的向量空间维数。'},
    {'id': 25, 'category': '线性代数', 'content': '计算向量 \( \mathbf{a}=(1, 2, 3) \) 和 \( \mathbf{b}=(4, 5, 6) \) 的点积数值。'},
    {'id': 26, 'category': '线性代数', 'content': '计算向量 \( \mathbf{a}=(1, 0, 0) \) 和 \( \mathbf{b}=(0, 1, 0) \) 的叉积向量。'},
    {'id': 27, 'category': '线性代数', 'content': '计算矩阵 \( A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix} \) 的秩。'},
    {'id': 28, 'category': '线性代数', 'content': '求二次型 \( f(x, y) = x^2 + 2xy + y^2 \) 的标准型。'},
    {'id': 29, 'category': '线性代数', 'content': '已知正交矩阵 \( A \)，若 \( |A| = 1 \)，求 \( A^T A \) 的结果矩阵。'},
    {'id': 30, 'category': '线性代数', 'content': '解线性方程组：\( x + y = 3, x - y = 1 \)，求 \( x \) 和 \( y \) 的值。'},
    {'id': 31, 'category': '概率统计', 'content': '投掷一枚均匀硬币 3 次，计算恰好出现 2 次正面的概率值。'},
    {'id': 32, 'category': '概率统计', 'content': '设 \( X \sim N(0, 1) \)，求 \( E(X^2) \) 的值。'},
    {'id': 33, 'category': '概率统计', 'content': '已知 \( P(A)=0.5, P(B)=0.4 \)，\( A \) 和 \( B \) 独立，计算 \( P(A \cap B) \) 的值。'},
    {'id': 34, 'category': '概率统计', 'content': '一盒中有 3 红 2 白球，不放回取 2 次，计算第二次取到红球的概率值。'},
    {'id': 35, 'category': '概率统计', 'content': '计算数据集 \( \{1, 2, 3, 4, 5\} \) 的方差值。'},
    {'id': 36, 'category': '概率统计', 'content': '若 \( X \) 服从参数为 \( \lambda \) 的泊松分布，求 \( E(X) \)。'},
    {'id': 37, 'category': '概率统计', 'content': '若 \( X \) 服从参数为 \( \lambda \) 的指数分布，求 \( P(X > 1/\lambda) \)。'},
    {'id': 38, 'category': '概率统计', 'content': '计算掷两个骰子点数之和为 7 的概率。'},
    {'id': 39, 'category': '概率统计', 'content': '若 \( X, Y \) 独立且均服从 \( U(0,1) \)，求 \( E(X+Y) \) 的值。'},
    {'id': 40, 'category': '概率统计', 'content': '已知 \( P(B|A)=0.8, P(A)=0.5, P(B)=0.6 \)，计算 \( P(A|B) \) 的值。'},
    {'id': 41, 'category': '基础数学', 'content': '分解质因数：将 100 分解为质数的乘积。'},
    {'id': 42, 'category': '基础数学', 'content': '计算 12 和 18 的最大公约数 (GCD)。'},
    {'id': 43, 'category': '基础数学', 'content': '计算 \( 1 + 2 + \dots + 100 \) 的和。'},
    {'id': 44, 'category': '基础数学', 'content': '已知直角三角形两直角边为 3 和 4，求斜边长度。'},
    {'id': 45, 'category': '基础数学', 'content': '计算复数 \( z = 1 + i \) 的模长 \( |z| \)。'},
    {'id': 46, 'category': '基础数学', 'content': '计算 \( e^{i\pi} + 1 \) 的值。'},
    {'id': 47, 'category': '基础数学', 'content': '解方程 \( x^2 - 2 = 0 \)，求正根的近似值（保留两位小数）。'},
    {'id': 48, 'category': '基础数学', 'content': '有 5 个鸽巢和 6 只鸽子，至少有几个鸽子在同一个巢里？'},
    {'id': 49, 'category': '基础数学', 'content': '计算斐波那契数列的第 10 项 (\( F_1=1, F_2=1 \))。'},
    {'id': 50, 'category': '基础数学', 'content': '计算逻辑表达式 (True AND False) OR (True) 的真值。'},
    {'id': 51, 'category': '高等数学', 'content': '写出函数 \( f(x) = \cos(x) \) 在 \( x=0 \) 处的泰勒级数展开式的前三项。'},
    {'id': 52, 'category': '高等数学', 'content': '求函数 \( f(x, y) = x^2y + \sin(xy) \) 对 \( x \) 的偏导数。'},
    {'id': 53, 'category': '高等数学', 'content': '计算由曲线 \( y = x \) 和 \( y = x^2 \) 所围成图形的面积。'},
    {'id': 54, 'category': '高等数学', 'content': '求二阶常系数齐次线性微分方程 \( y\'\' - 4y = 0 \) 的通解。'},
    {'id': 55, 'category': '高等数学', 'content': '计算三元函数 \( f(x, y, z) = xyz \) 的梯度向量在点 \( (1, 1, 1) \) 处的值。'},
    {'id': 56, 'category': '高等数学', 'content': '计算三重积分 \( \iiint_V dV \)，其中 \( V \) 是单位球体 \( x^2 + y^2 + z^2 \leq 1 \)。'},
    {'id': 57, 'category': '高等数学', 'content': '求函数 \( f(x) = \ln(1+x) \) 的定义域。'},
    {'id': 58, 'category': '高等数学', 'content': '判断级数 \( \sum_{n=1}^{\infty} \frac{1}{n} \) 的敛散性。'},
    {'id': 59, 'category': '高等数学', 'content': '计算参数方程 \( x = \cos t, y = \sin t \) 在 \( t = \pi/4 \) 处的斜率。'},
    {'id': 60, 'category': '高等数学', 'content': '利用分部积分法计算 \( \int \ln(x) dx \)。'},
    {'id': 61, 'category': '线性代数', 'content': '已知矩阵 \( A = \text{diag}(1, 2, 3) \)，求其逆矩阵 \( A^{-1} \)。'},
    {'id': 62, 'category': '线性代数', 'content': '若 3阶矩阵 \( A \) 的特征值为 1, 2, 3，求矩阵的行列式 \( |A| \)。'},
    {'id': 63, 'category': '线性代数', 'content': '判断向量 \( \mathbf{v}_1 = (1, 2) \) 与 \( \mathbf{v}_2 = (-2, 1) \) 是否正交。'},
    {'id': 64, 'category': '线性代数', 'content': '计算矩阵 \( A = \begin{pmatrix} 1 & 0 \\ 2 & 1 \end{pmatrix} \) 的平方 \( A^2 \)。'},
    {'id': 65, 'category': '线性代数', 'content': '求矩阵 \( A = \begin{pmatrix} 1 & 2 \\ 2 & 4 \end{pmatrix} \) 的迹 (Trace)。'},
    {'id': 66, 'category': '线性代数', 'content': '已知 \( \mathbf{a} = (1, 1) \)，求 \( \mathbf{a} \) 在 \( \mathbf{b} = (1, 0) \) 上的投影向量。'},
    {'id': 67, 'category': '线性代数', 'content': '若 3x3 矩阵 \( A \) 的秩为 2，问齐次线性方程组 \( A\mathbf{x} = \mathbf{0} \) 的基础解系维数。'},
    {'id': 68, 'category': '线性代数', 'content': '计算 \( n \) 阶单位矩阵 \( I_n \) 的行列式值。'},
    {'id': 69, 'category': '线性代数', 'content': '求矩阵 \( A = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix} \) 的特征向量。'},
    {'id': 70, 'category': '线性代数', 'content': '已知矩阵 \( A, B \) 为 \( n \) 阶方阵，写出 \( (AB)^T \) 的展开式。'},
    {'id': 71, 'category': '概率统计', 'content': '设 \( X \sim B(10, 0.5) \)，求随机变量 \( X \) 的数学期望 \( E(X) \)。'},
    {'id': 72, 'category': '概率统计', 'content': '已知 \( P(A) = 0.3, P(B) = 0.4 \)，若 \( A, B \) 互斥，求 \( P(A \cup B) \)。'},
    {'id': 73, 'category': '概率统计', 'content': '计算标准正态分布密度函数在 \( x=0 \) 处的值。'},
    {'id': 74, 'category': '概率统计', 'content': '设 \( X, Y \) 独立且方差分别为 1 和 2，求 \( D(X-Y) \)。'},
    {'id': 75, 'category': '概率统计', 'content': '若随机变量 \( X \) 只有两个等概率取值，计算其信息熵 \( H(X) \)（bit）。'},
    {'id': 76, 'category': '概率统计', 'content': '求数据组 {2, 4, 4, 4, 5, 5, 7, 9} 的众数。'},
    {'id': 77, 'category': '概率统计', 'content': '若 \( X \) 服从参数为 2 的指数分布，求 \( x > 0 \) 时的概率密度函数表达式。'},
    {'id': 78, 'category': '概率统计', 'content': '计算随机变量 \( X \sim U(0, 10) \) 落在区间 \([2, 5]\) 的概率。'},
    {'id': 79, 'category': '概率统计', 'content': '已知 \( E(X)=2, D(X)=4 \)，计算 \( E(X^2) \)。'},
    {'id': 80, 'category': '概率统计', 'content': '写出切比雪夫不等式中用于估计概率上界的公式。'},
    {'id': 81, 'category': '数值分析', 'content': '写出牛顿迭代法求方程 \( f(x)=0 \) 根的迭代公式。'},
    {'id': 82, 'category': '数值分析', 'content': '在数值积分中，写出复化梯形公式计算 \( \int_a^b f(x) dx \) 的形式。'},
    {'id': 83, 'category': '数值分析', 'content': '已知点 \( (0, 1) \) 和 \( (1, 3) \)，求过这两点的拉格朗日插值多项式。'},
    {'id': 84, 'category': '数值分析', 'content': '写出常微分方程数值解中的显式欧拉法迭代公式。'},
    {'id': 85, 'category': '计算机数学', 'content': '计算二进制数 1011 转换为十进制后的数值。'},
    {'id': 86, 'category': '数值分析', 'content': '简述线性方程组雅可比迭代法收敛的一个充分条件。'},
    {'id': 87, 'category': '数值分析', 'content': '写出函数 \( f(x) = x^2 \) 在点 \( x=1 \) 处步长为 \( h \) 的前向差分表达式。'},
    {'id': 88, 'category': '数值分析', 'content': '解释什么是矩阵的条件数，以及它对数值稳定性的影响。'},
    {'id': 89, 'category': '数值分析', 'content': '用二分法求 \( f(x)=x^2-2=0 \) 在 \([1, 2]\) 内的根，第一步后的中点值。'},
    {'id': 90, 'category': '数值分析', 'content': '简述高斯消去法中“按列选主元”的目的。'},
    {'id': 91, 'category': '基础数学', 'content': '若 \( A=\{1, 2\}, B=\{2, 3\} \)，求 \( A \cup B \)。'},
    {'id': 92, 'category': '基础数学', 'content': '计算复数 \( (1+i)^2 \) 的最简形式。'},
    {'id': 93, 'category': '基础数学', 'content': '写出欧拉公式 \( e^{ix} \) 的展开表达式。'},
    {'id': 94, 'category': '基础数学', 'content': '求复数 \( z = 3 + 4i \) 的模长。'},
    {'id': 95, 'category': '基础数学', 'content': '判断命题公式 \( P \lor \neg P \) 的真值类型（永真/永假）。'},
    {'id': 96, 'category': '基础数学', 'content': '计算 \( 5! \)（5的阶乘）的数值。'},
    {'id': 97, 'category': '基础数学', 'content': '求直角坐标点 \( (1, \sqrt{3}) \) 对应的极坐标 \( (r, \theta) \)。'},
    {'id': 98, 'category': '基础数学', 'content': '写出双曲正弦函数 \( \sinh(x) \) 的指数定义式。'},
    {'id': 99, 'category': '基础数学', 'content': '计算等比数列 \( 1, 1/2, 1/4, \dots \) 的各项之和。'},
    {'id': 100, 'category': '基础数学', 'content': '在包含 10 个顶点的完全图 \( K_{10} \) 中共有多少条边？'}
]