QUESTION_BANK = [
    {'id': 1, 'category': '题目1', 'content': '求函数 f(x) = x³ - 3x + 1 的极大值点。'},
    {'id': 2, 'category': '题目2', 'content': '计算不定积分 ∫ x * e^x dx。'},
    {'id': 3, 'category': '题目3', 'content': '求极限 lim (x→0) (sin(x) / x)。'},
    {'id': 4, 'category': '题目4', 'content': '已知 y = ln(tan(x))，求 dy/dx。'},
    {'id': 5, 'category': '题目5', 'content': '计算定积分 ∫(0 to π) sin(x) dx。'},
    {'id': 6, 'category': '题目6', 'content': '求曲线 y = x² 在 x = 1 处的切线方程。'},
    {'id': 7, 'category': '题目7', 'content': '求级数 ∑(1/2^n) (n=1 to ∞) 的和。'},
    {'id': 8, 'category': '题目8', 'content': '求函数 f(x, y) = x² + y² 的梯度向量 grad(f) 在点 (1, 2) 的值。'},
    {'id': 9, 'category': '题目9', 'content': '计算二重积分 ∬ (x + y) dxdy，区域 D 为 0≤x≤1, 0≤y≤1。'},
    {'id': 10, 'category': '题目10', 'content': '求微分方程 y\' + y = 0 满足初值 y(0)=1 的特解。'},
    {'id': 11, 'category': '题目11', 'content': '求函数 f(x) = x * |x| 的导函数 f\'(x)。'},
    {'id': 12, 'category': '题目12', 'content': '利用洛必达法则计算 lim (x→∞) (ln(x) / x)。'},
    {'id': 13, 'category': '题目13', 'content': '写出函数 f(x) = e^x 的麦克劳林级数的前三项。'},
    {'id': 14, 'category': '题目14', 'content': '计算圆 x² + y² = 4 围成的面积值。'},
    {'id': 15, 'category': '题目15', 'content': '计算曲线 y=x² 从 x=0 到 x=1 的弧长积分表达式。'},
    {'id': 16, 'category': '题目16', 'content': '求 z = x² - y² 在点 (0,0) 处的黑塞矩阵 (Hessian Matrix)。'},
    {'id': 17, 'category': '题目17', 'content': '计算向量场 F = (y, -x) 的散度数值。'},
    {'id': 18, 'category': '题目18', 'content': '计算向量场 F = (y, -x, 0) 的旋度向量。'},
    {'id': 19, 'category': '题目19', 'content': '求微分方程 y\'\' + y = 0 满足 y(0)=0, y\'(0)=1 的特解。'},
    {'id': 20, 'category': '题目20', 'content': '求函数 f(x) = x² 在区间 [0, 2] 上满足拉格朗日中值定理的 ξ 值。'},
    {'id': 21, 'category': '题目21', 'content': '计算行列式 |A| 的值，其中 A = [[1, 2], [3, 4]]。'},
    {'id': 22, 'category': '题目22', 'content': '计算矩阵 A = [[1, 1], [0, 1]] 的逆矩阵。'},
    {'id': 23, 'category': '题目23', 'content': '计算矩阵 A = [[2, 0], [0, 3]] 的特征值。'},
    {'id': 24, 'category': '题目24', 'content': '求向量组 a1=(1,0), a2=(0,1) 生成的向量空间维数。'},
    {'id': 25, 'category': '题目25', 'content': '计算向量 a=(1, 2, 3) 和 b=(4, 5, 6) 的点积数值。'},
    {'id': 26, 'category': '题目26', 'content': '计算向量 a=(1, 0, 0) 和 b=(0, 1, 0) 的叉积向量。'},
    {'id': 27, 'category': '题目27', 'content': '计算矩阵 A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] 的秩。'},
    {'id': 28, 'category': '题目28', 'content': '求二次型 f(x, y) = x² + 2xy + y² 的标准型。'},
    {'id': 29, 'category': '题目29', 'content': '已知正交矩阵 A，若 |A| = 1，求 A 的转置与 A 的乘积。'},
    {'id': 30, 'category': '题目30', 'content': '解线性方程组：x + y = 3, x - y = 1，求 x 和 y 的值。'},
    {'id': 31, 'category': '题目31', 'content': '投掷一枚均匀硬币 3 次，计算恰好出现 2 次正面的概率值。'},
    {'id': 32, 'category': '题目32', 'content': '设 X ~ N(0, 1)，求 E(X²) 的值。'},
    {'id': 33, 'category': '题目33', 'content': '已知 P(A)=0.5, P(B)=0.4, A和B独立，计算 P(A∩B) 的值。'},
    {'id': 34, 'category': '题目34', 'content': '一盒中有3红2白球，不放回取2次，计算第二次取到红球的概率值。'},
    {'id': 35, 'category': '题目35', 'content': '计算数据集 {1, 2, 3, 4, 5} 的方差值。'},
    {'id': 36, 'category': '题目36', 'content': '若 X 服从参数为 λ 的泊松分布，求 E(X)。'},
    {'id': 37, 'category': '题目37', 'content': '若 X 服从参数为 λ 的指数分布，求 P(X > 1/λ)。'},
    {'id': 38, 'category': '题目38', 'content': '计算掷两个骰子点数之和为 7 的概率。'},
    {'id': 39, 'category': '题目39', 'content': '若 X, Y 独立且均服从 U(0,1)，求 E(X+Y) 的值。'},
    {'id': 40, 'category': '题目40', 'content': '已知 P(B|A)=0.8, P(A)=0.5, P(B)=0.6，计算 P(A|B) 的值。'},
    {'id': 41, 'category': '题目41', 'content': '分解质因数：将 100 分解为质数的乘积。'},
    {'id': 42, 'category': '题目42', 'content': '计算 12 和 18 的最大公约数 (GCD)。'},
    {'id': 43, 'category': '题目43', 'content': '计算 1 + 2 + ... + 100 的值。'},
    {'id': 44, 'category': '题目44', 'content': '已知直角三角形两直角边为 3 和 4，求斜边长度。'},
    {'id': 45, 'category': '题目45', 'content': '计算复数 z = 1 + i 的模长 |z|。'},
    {'id': 46, 'category': '题目46', 'content': '计算 e^(iπ) + 1 的值。'},
    {'id': 47, 'category': '题目47', 'content': '解方程 x² - 2 = 0，求正根的近似值（保留两位小数）。'},
    {'id': 48, 'category': '题目48', 'content': '有 5 个鸽巢和 6 只鸽子，至少有几个鸽子在同一个巢里？'},
    {'id': 49, 'category': '题目49', 'content': '计算斐波那契数列的第 10 项 (F1=1, F2=1)。'},
    {'id': 50, 'category': '题目50', 'content': '计算逻辑表达式 (True AND False) OR (True) 的真值。'}
]